site_name: ToolNotes
theme:
    name: material
nav:
    - 简介: index.md
    - Vim:
        - 移动大法: vim/move.md
        - 增删改查: vim/edit.md
        - 分屏大法: vim/split.md
        - 注释大法: vim/comment.md
        - 缩进大法: vim/indent.md